### ISSUE TITLE
Potential serialport version problem

### ISSUE THREAD

**Issue by dougtoppin** [jamesnesfield/node-waterrower#4]
Using OSX 10.11.1 Beta, Node v4.2.1 and Python 2.7.10. I had a problem with the serialport version "^1.4.10" causing a number of npm install errors. I am sure that this is due to my configuration but wanted to pass it along in case anyone else had a similar problem.
If I change the package.json to "serialport": "^2.0.0" it installed and ran fine.

The errors started like this after npm install.

  CXX(target) Release/obj.target/serialport/src/serialport.o
In file included from ../src/serialport.cpp:3:
In file included from ../src/serialport.h:5:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);

**Comment by jamesnesfield** [comment]
thanks for the pull request Doug. Appreciated.
